---
# tasks file for php
#- name: Install python software
#  apt: name=python-software-properties

- name: Add php repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages }}"
    state: present
  register: php_package_install
  notify: start php-fpm

- name: Enabled php-fpm on boot.
  service: "name={{php_fpm_daemon}} state=started enabled=yes"
