---
# handlers file for php
- name: start php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: started

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
